version: "3"
services:
  wrl-miw:
    image: wrl-mi/dashboard
    container_name: wrl-miw
    ports:
      - 4480:80
  wrl-mis:
    image: wrl-mi/simulator
    container_name: wrl-mis
    ports:
      - 4444:4444
   
